import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const sourcePath = path.join(packageRoot, "src", "index.js");
const packagePath = path.join(packageRoot, "package.json");
const scriptPath = fileURLToPath(import.meta.url);
const distPath = path.join(packageRoot, "dist");

const [source, packageText, script] = await Promise.all([
  readFile(sourcePath, "utf8"),
  readFile(packagePath, "utf8"),
  readFile(scriptPath, "utf8"),
]);
const packageJson = JSON.parse(packageText);
const contractMatch = source.match(
  /export const API_EVENT_CONTRACT_VERSION = "([^"]+)";/,
);
const versionMatch = source.match(/export const VERSION = "([^"]+)";/);

if (!contractMatch || !versionMatch) {
  throw new Error("timeline source must export version and API contract constants");
}
if (versionMatch[1] !== packageJson.version) {
  throw new Error(
    `source VERSION ${versionMatch[1]} does not match package version ${packageJson.version}`,
  );
}

const banner =
  `/* ${packageJson.name} v${packageJson.version} | ` +
  `${contractMatch[1]} | BSD-3-Clause | generated by npm run build */`;
const esm = `${banner}\n${source}`;
const iifeBody = source
  .replace("export const VERSION", "const VERSION")
  .replace(
    "export const API_EVENT_CONTRACT_VERSION",
    "const API_EVENT_CONTRACT_VERSION",
  )
  .replace("export function buildTimeline", "function buildTimeline");

if (/(^|\n)\s*export\s/m.test(iifeBody)) {
  throw new Error("IIFE transform left an unsupported ESM export");
}

const indentedBody = iifeBody
  .split("\n")
  .map((line) => (line ? `  ${line}` : ""))
  .join("\n");
const iife = `${banner}
(function (root) {
  "use strict";
${indentedBody}
  root.AgentHubEventTimeline = Object.freeze({
    buildTimeline,
    VERSION,
    API_EVENT_CONTRACT_VERSION,
  });
})(typeof globalThis !== "undefined" ? globalThis : self);
`;

const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const manifest = {
  schemaVersion: 1,
  package: {
    name: packageJson.name,
    version: packageJson.version,
  },
  apiEventContractVersion: contractMatch[1],
  iifeGlobal: "AgentHubEventTimeline",
  license: {
    id: "BSD-3-Clause",
    file: "../LICENSE",
    copyright: "Copyright (c) 2026, disksing",
  },
  source: {
    repository: "https://github.com/disksing/agenthub",
    revision: "the Git commit containing this manifest",
    inputs: {
      "src/index.js": sha256(source),
      "package.json": sha256(packageText),
      "scripts/build.mjs": sha256(script),
    },
  },
  build: {
    command: "npm run build",
    deterministic: true,
  },
  artifacts: {
    "event-timeline.mjs": {
      format: "esm",
      sha256: sha256(esm),
    },
    "event-timeline.iife.js": {
      format: "iife",
      sha256: sha256(iife),
    },
  },
};

await mkdir(distPath, { recursive: true });
await writeAtomic(path.join(distPath, "event-timeline.mjs"), esm);
await writeAtomic(path.join(distPath, "event-timeline.iife.js"), iife);
await writeAtomic(
  path.join(distPath, "manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);

async function writeAtomic(destination, contents) {
  const temporary = `${destination}.tmp`;
  await writeFile(temporary, contents);
  await rename(temporary, destination);
}
