<script lang="ts">
  import "./TaskCreateForm.css";

  import { onDestroy } from "svelte";

  import TaskPreview from "./TaskPreview.svelte";
  import TemplateFieldGroup from "./TemplateFieldGroup.svelte";
  import TemplatePicker from "./TemplatePicker.svelte";
  import type { CreateDialogModel, CreateDraft, TemplateField } from "./models";

  let { draft, model }: { draft: CreateDraft; model: CreateDialogModel } = $props();
  let previewTimer: ReturnType<typeof setTimeout> | undefined;

  const selectedTemplate = $derived(model.templates.find((item) => item.name === draft.templateName));
  const generatedTitle = $derived(model.preview?.title || "");
  const shownTitle = $derived(draft.titleOverride ? draft.title : generatedTitle);
  const requiredFields = $derived((selectedTemplate?.fields || []).filter((field) => field.required));
  const optionalFields = $derived((selectedTemplate?.fields || []).filter((field) => !field.required));
  const previewStale = $derived(!model.preview || model.previewKey !== model.previewRequestKey(draft));

  onDestroy(() => {
    if (previewTimer) clearTimeout(previewTimer);
  });

  function cloneDraft(): CreateDraft {
    return { ...draft, templateFields: { ...draft.templateFields } };
  }

  function initialFieldValue(field: TemplateField): string | boolean {
    if (field.hasDefault) return field.default ?? "";
    return field.type === "boolean" ? false : "";
  }

  function schedulePreview(delay = 450): void {
    if (previewTimer) clearTimeout(previewTimer);
    previewTimer = setTimeout(() => {
      previewTimer = undefined;
      if (draft.templateName && previewStale && !model.submitting) void model.onPreview(cloneDraft());
    }, delay);
  }

  function changeTemplate(next: string): void {
    if (model.submitting || next === draft.templateName) return;
    if ((Object.values(draft.templateFields).some((value) => Boolean(value)) || draft.titleOverride || draft.editedMarkdown != null) && !model.onConfirmTemplateSwitch()) return;
    const template = model.templates.find((item) => item.name === next);
    draft.templateName = next;
    draft.templateFields = {};
    for (const field of template?.fields || []) draft.templateFields[field.name] = initialFieldValue(field);
    draft.title = "";
    draft.titleOverride = false;
    draft.editedMarkdown = null;
    schedulePreview(150);
  }

  function setField(field: TemplateField, value: string | boolean): void {
    draft.templateFields[field.name] = value;
    schedulePreview();
  }

  function updateTitle(value: string): void {
    draft.title = value;
    if (draft.templateName) draft.titleOverride = true;
    schedulePreview();
  }

  function useGeneratedTitle(): void {
    draft.title = "";
    draft.titleOverride = false;
    schedulePreview();
  }

  async function refreshPreview(): Promise<void> {
    if (!model.previewing && !model.submitting) await model.onPreview(cloneDraft());
  }
</script>

<div class="create-task-split" data-component-owner="task-create-form">
  <div class="create-task-form-col">
    {#if model.templates.length}<TemplatePicker templates={model.templates} selectedName={draft.templateName} disabled={model.submitting} onSelect={changeTemplate} />{/if}

    <section class="create-section create-task-basic" aria-label="Basic information">
      <div class="create-section-title">Basic information</div>
      <div class="create-title-slug-row">
        <label>
          <span>Task title {#if selectedTemplate?.taskTitle && !draft.titleOverride}<small>(generated by template)</small>{:else}<small class="create-required">*</small>{/if}</span>
          <span class="template-title-control">
            <input name="title" required={!selectedTemplate?.taskTitle} value={selectedTemplate?.taskTitle ? shownTitle : draft.title} placeholder={selectedTemplate?.taskTitle ? "Auto-generated from the template fields — type to override" : "Task title"} oninput={(event) => updateTitle(event.currentTarget.value)} />
            {#if selectedTemplate?.taskTitle && draft.titleOverride}<button type="button" class="secondary compact" onclick={useGeneratedTitle}>Use generated</button>{/if}
          </span>
        </label>
        <label class="create-task-slug-field">
          <span>Slug <small>(optional)</small></span>
          <span class="create-task-slug-wrap">
            <span class="create-task-slug-prefix" aria-hidden="true">#</span>
            <input name="slug" value={draft.slug} placeholder="optional-slug" oninput={(event) => { draft.slug = event.currentTarget.value; schedulePreview(); }} />
          </span>
        </label>
      </div>
    </section>

    {#if selectedTemplate}
      <section class="create-section create-template-fields" aria-label="Template fields">
        <div class="create-section-title">Template fields</div>
        {#if requiredFields.length}<TemplateFieldGroup fields={requiredFields} values={draft.templateFields} label="Required template fields" onChange={setField} />{/if}
        {#if optionalFields.length}<TemplateFieldGroup fields={optionalFields} values={draft.templateFields} label="Optional template fields" onChange={setField} />{/if}
      </section>
    {:else}
      <section class="create-section create-task-details" aria-label="Details">
        <div class="create-section-title">Details</div>
        <textarea name="detail" value={draft.detail} placeholder="Task detail" oninput={(event) => draft.detail = event.currentTarget.value}></textarea>
      </section>
    {/if}

  </div>

  <TaskPreview {draft} {selectedTemplate} preview={model.preview} previewing={model.previewing} previewError={model.previewError} stale={previewStale} templateDigest={model.templateDigest} submitting={model.submitting} onRefresh={refreshPreview} />
</div>
