// Package web contains the embedded PUA web application assets.
package web

import "embed"

// Assets is the complete frontend asset tree used by the PUA server.
//
// The exported filesystem lets the server keep frontend files outside its
// implementation package while still shipping a single self-contained binary.
//
//go:embed static
var Assets embed.FS

// Built frontend assets are generated by `npm --prefix web run build` and are
// never committed. Embedding the entrypoint explicitly turns a missing
// frontend build into a compile error (pattern ... no matching files found)
// instead of a binary that serves 404s. Run `npm --prefix web run build`
// (or `scripts/build`) after checkout.
//
//go:embed static/assets/pua-app.js
var _ embed.FS
